Dirs = OnvifServer

all: $(Dirs)
$(Dirs):
	make -C $@ all

install clean distclean:
	$(Dirs:%=make $@ -C % &&) echo $@ done!

%:
	$(Dirs:%=make $@ -C % &&) echo $@ done!

.PHONY: all install clean distclean $(Dirs)