#!/bin/sh
#rem config <ip> <port> <id> passwd> <xml folder>
source ~/prj/bin/myprj

Argc=$#
Configexe=~/prj/$Myprj/console/console/project_window/$WHBS_CONSOLE_TARGETID/release/config.exe
Folder=ttt

if [ $Argc -lt 1 ]; then
	echo ip 끝자리는?
	exit 0
fi

if [ $Argc -gt 1 ]; then
	Folder=$2
	echo 폴더는 $Folder임
fi

if [ ! -f "$Configexe" ]; then
	echo config.exe가 없는 거 같다
	exit 0
fi

if [ "${1:0:1}" = "0" ]; then
	eee $Configexe 192.168.110.${1:1:3} 80 admin 12345 --path:$Folder
else
	eee $Configexe 192.168.217.$1 80 admin 12344 --path:$Folder
fi