#!/bin/sh
#rem config <ip> <port> <id> passwd> <xml folder>
source ~/prj/bin/myprj

Argc=$#
Configexe=~/prj/$Myprj/console/console/project_window/$WHBS_CONSOLE_TARGETID/release/config.exe
Folder=--path:$1
Passwd=1111111qQ
#Passwd=12345

if [ $Argc -lt 1 ]; then
	echo ip 끝자리는?
	exit 0
fi

#arg0
if [ $0 != "./runccc" ]; then
	Tls=-tls
fi

#arg1, see https://stackoverflow.com/questions/806906/how-do-i-test-if-a-variable-is-a-number-in-bash
re='^[0-9]+$'
if ! [[ $1 =~ $re ]]; then
	echo null ip 는 help임
elif [ "${1:0:1}" = "0" ]; then
	Ipaddr=192.168.110.${1:1:3}
else
	Ipaddr=192.168.217.$1
fi

#arg2
if [ $Argc -gt 1 ]; then
	Passwd=$2
	echo 암호는 $Passwd임
fi

#arg3: help를 원한다면 --help
if [ $Argc -gt 2 ]; then
	Folder=$3
	echo 폴더는 $Folder임
fi

if [ ! -f "$Configexe" ]; then
	echo config.exe가 없는 거 같다
	exit 0
fi

eee $Configexe $Ipaddr 80 admin $Passwd $Folder $Tls
