#!/bin/sh
#rem config <ip> <port> <id> passwd> <xml folder>

Argc=$#
Configexe=/home/tsp/prj/console/console/project_window/$WHBS_CONSOLE_TARGETID/release/config.exe

if [ $Argc -lt 1 ]; then
	echo ip 끝자리는?
	exit 0
fi
if [ ! -f "$Configexe" ]; then
	echo config.exe가 없는 거 같다
	exit 0
fi

if [ "${1:0:1}" = "0" ]; then
	eee $Configexe 192.168.110.$1 80 admin 12345 --path:ttt
else
	eee $Configexe 192.168.217.$1 80 admin 12345 --path:ttt
fi