#!/bin/ash

source /wgi_sys_vars_definition

if [ ${vga_output_type} = ${VGA_OUTPUT_TYPE_0} ]; then
FB_NO=1
else
FB_NO=0
fi

Oem=webgate
OModel=${Oem}_$1
Version=`awk -F: '{print $2}' /version`

if [[ ! "$1" ]]; then
	echo 모델은?
	exit 0
fi

if [[ "$2" && "$2" = "--initxml" ]]; then
	for i in . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
	do
		echo -e "xml 초기화 한다 한다 한다.\a"
	done
	sleep 1

	cp project_linux/$OModel/*.xml /usr/edvr -f
	sed -i '/general_fw_version/,/general_fw_version/ s:<string>.*</string>:<string>'${Version}'</string>:' /usr/edvr/dvrconfig_default.xml
fi

Arg=$2 $3 $4 $5
../hidvr/console/qt/examples/qws/console/project_linux/$OModel/$OModel $Arg -qws -display linuxfb:/dev/fb${FB_NO}:size=1920x1080:qws_size=1920x1080:depth=32:mmWidth:480:mmHeight=270 -nokeyboard -font /usr/lib/qt/lib/fonts/arial.ttf
