#!/bin/bash

if svn info 2>/dev/null; then
	Cmd=TortoiseProc.exe
else
	Cmd=TortoiseGitProc.exe
fi

case $1 in
	"l")
	$Cmd /command:log $2 $3 $4 $5&
	;;

	"m")
	$Cmd /command:diff $2 $3 $4 $5&
	;;

	'r')
	$Cmd /command:repobrowser $2 $3 $4 $5&
	;;

	'b')
	$Cmd /command:blame $2 $3 $4 $5&
	;;

	"ci")
	$Cmd /command:commit $2 $3 $4 $5&
	;;

	*)
	echo "사용법: ee <l|m|ci> [options]"
	echo "ex) ee l /path:./hi.txt"
	;;
esac
