#!/bin/bash

SvnInfoUrl=`svn info|grep ^URL:|awk '{print $2}'`

if [ $# -gt 2 ]; then
	Where=$SvnInfoUrl/$2
else
	Where=$SvnInfoUrl
fi
echo "path: $Where임"

case $1 in
	"l")
	TortoiseProc.exe /command:log /path:$Where
	;;
	
#	"m")
#	TortoiseProc.exe /command:diff /path:$WslPrefix$Where
#	;;
	
#	"ci")
#	TortoiseProc.exe /command:commit /path:$WslPrefix$Where
#	;;
	
	*)
	echo "사용법: ee <l> [path]"
	;;
esac
